In [66]:
import numpy as np
import pandas as pd

## Arrays en NumPy

In [67]:
escalar = np.array(42)
print(type(escalar))
print(escalar)


<class 'numpy.ndarray'>
42


In [68]:
vector = np.array([30, 29, 42, 35, 33 , 36, 32])
print(vector)

[30 29 42 35 33 36 32]


In [69]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [70]:
tensor = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(tensor)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


### metodo array

In [71]:
array_arange = np.arange(10)
print(array_arange)

[0 1 2 3 4 5 6 7 8 9]


## Matrix identidad

In [72]:
eye_matrix = np.eye(6)
print(eye_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


### Matrix diagonal

In [73]:
diag = np.diag([1,2,3])
print(diag)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


### Random

In [74]:
random = np.random.random((2,3))
print(random)

[[0.3219044  0.58079771 0.60438595]
 [0.57089963 0.63868374 0.30442039]]


## Arrays en NumPy

In [75]:
array = np.array([[1,2,3],[4,5,6]])
print(array.ndim)
print(array.shape)
print(array.dtype)

2
(2, 3)
int64


In [76]:
z = np.array(3, dtype=np.uint8)
print(z)

3


In [77]:
double_array = np.array([1,2,3], dtype='d')
print(double_array)

[1. 2. 3.]


In [78]:
z = z.astype(np.float64)
print(z)

3.0


### Suma

In [79]:
array = np.array([[1,2,3],[4,5,6]])
sum = np.sum(array)
print(sum)

21


## Media

In [80]:
mean = np.mean(array)
print(mean)

3.5


### Desviación estándar

In [81]:
std = np.std(array)
print(std)

1.707825127659933


Broadcarting

In [82]:
price = np.array([100, 200, 300])
discount = np.array([0.9])
discount_price = price * discount
print(discount_price)

[ 90. 180. 270.]


In [83]:
price = np.random.randint(100, 500, size =(3, 3))
discount = np.array([10, 20, 30])
discount_price = price + discount
print(price)
print(discount_price)

[[199 172 261]
 [499 145 437]
 [235 476 303]]
[[209 192 291]
 [509 165 467]
 [245 496 333]]


In [84]:
array = np.array([1,2,3,4,5])
print(np.all(array > 9))

False


In [85]:
print(np.any(array > 0))

True


In [86]:
array_a = np.array([1,2,3])
array_b = np.array([4,5,6])
concatenated_a = np.concatenate((array_a, array_a))
concatenated_ab = np.concatenate((array_a, array_b))
print(concatenated_a)
print(concatenated_ab)

[1 2 3 1 2 3]
[1 2 3 4 5 6]


In [87]:
stacked_v = np.vstack((array_a, array_b))
print(stacked_v)

[[1 2 3]
 [4 5 6]]


In [88]:
stacked_h = np.hstack((array_a, array_b))
print(stacked_h)

[1 2 3 4 5 6]


In [89]:
array_c = np.arange(1,10)
split_array = np.split(array_c,3)
print(array_c)
print(split_array)


[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


## Unique

In [92]:
survey_responses = np.array(["bueno", "excelente", "malo",
                            "bueno", "malo", "excelente",
                            "bueno", "bueno", "malo",
                            "excelente", "excelente", "excelente"])

print(np.unique(survey_responses))

['bueno' 'excelente' 'malo']


In [93]:
unique_elements , count = np.unique(survey_responses, return_counts=True)
print(unique_elements)
print(count)

['bueno' 'excelente' 'malo']
[4 5 3]


In [95]:
array_x = np.arange(10)
view_y = array_x[1:3]
print(array_x)
print(view_y)
array_x[1:3] = [10, 11]
print(array_x)
print(view_y)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[10 11]


In [103]:
array_x = np.arange(10)
copy_x = array_x[[1,2]]
print(array_x)
print(copy_x)
array_x[1:3] = [10, 11]
print(array_x)
print(copy_x)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[1 2]


## Transformación de Arrays

In [105]:
matrix = np.array([[1,2,3,],[4,5,6],[7,8,9]])
transposed_matrix = matrix.T
print(matrix)
print(transposed_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [110]:
array = np.arange(1,13)
reshaped_array = array.reshape(3,4)
print(array)
print(reshaped_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [111]:
reversed_array = array[::-1]
print(array)
print(reversed_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[12 11 10  9  8  7  6  5  4  3  2  1]


In [112]:
matrix = np.array([[1,2,3,],[4,5,6],[7,8,9]])
flattened_array = matrix.flatten()
print(matrix)
print(flattened_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
