In [2]:
import numpy as np
import pandas as pd

## Arrays en NumPy

In [3]:
escalar = np.array(42)
print(type(escalar))
print(escalar)


<class 'numpy.ndarray'>
42


In [4]:
vector = np.array([30, 29, 42, 35, 33 , 36, 32])
print(vector)

[30 29 42 35 33 36 32]


In [5]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
tensor = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(tensor)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


### metodo array

In [10]:
array_arange = np.arange(10)
print(array_arange)

[0 1 2 3 4 5 6 7 8 9]


## Matrix identidad

In [12]:
eye_matrix = np.eye(6)
print(eye_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


### Matrix diagonal

In [ ]:
diag = np.diag([1,2,3])
print(diag)

### Random

In [13]:
random = np.random.random((2,3))
print(random)

[[0.07421435 0.42518183 0.2412923 ]
 [0.37860865 0.26405434 0.59020446]]


## Arrays en NumPy

In [14]:
array = np.array([[1,2,3],[4,5,6]])
print(array.ndim)
print(array.shape)
print(array.dtype)

2
(2, 3)
int64


In [15]:
z = np.array(3, dtype=np.uint8)
print(z)

3


In [16]:
double_array = np.array([1,2,3], dtype='d')
print(double_array)

[1. 2. 3.]


In [17]:
z = z.astype(np.float64)
print(z)

3.0


### Suma

In [18]:
array = np.array([[1,2,3],[4,5,6]])
sum = np.sum(array)
print(sum)

21


## Media

In [19]:
mean = np.mean(array)
print(mean)

3.5


### Desviación estándar

In [20]:
std = np.std(array)
print(std)

1.707825127659933
