In [1]:
import numpy as np

In [3]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[2,3],[2,1]])
C = np.array([[3,1],[4,2]])

In [5]:
# Asociativa

ABC = A.dot(B.dot(C))
print(ABC)

[[ 66  28]
 [160  68]
 [328 140]]


In [6]:
AB_C = A.dot(B).dot(C)
print(AB_C)

[[ 66  28]
 [160  68]
 [328 140]]


In [8]:
# Distributiva

D = A.dot(B+C)
E = (A.dot(B)) + (A.dot(C))

In [9]:
print(D)
print(E)

[[ 28  17]
 [ 67  41]
 [133  83]]
[[ 28  17]
 [ 67  41]
 [133  83]]


In [10]:
print(D==E)

[[ True  True]
 [ True  True]
 [ True  True]]


In [11]:
F = B.dot(C)

In [12]:
G = C.dot(B)

In [13]:
print(F==G)

[[False False]
 [False False]]


In [14]:
print(F)

[[18  8]
 [10  4]]


In [15]:
print(G)

[[ 8 10]
 [12 14]]


In [16]:
v1 = np.array([[2],[7]])
v2 = np.array([[3],[5]])

In [18]:
v1_tv2 = v1.T.dot(v2)
v2_tv1 = v2.T.dot(v1)

In [19]:
print(v1_tv2)

[[41]]


In [20]:
print(v2_tv1)

[[41]]
