In [1]:
import numpy as np

## Scalar

In [3]:
x = np.array(42)
print(x.shape)
x.ndim

()


0

## Vector

In [4]:
x = np.array([42, 2, 5, 3, 6, 7])
print(x.shape)
x.ndim

(6,)


1

## Matrix

In [5]:
x = np.array([[42, 2, 5, 3, 6, 7],
             [66, 2, 7, 3, 9, 8]])
print(x.shape)
x.ndim

(2, 6)


2

## Tensor

In [8]:
x = np.array([[[42, 2, 5, 3, 6, 7],
             [66, 2, 7, 3, 9, 8]],
             [[42, 2, 5, 3, 6, 7],
             [66, 2, 7, 3, 9, 8]],
             [[42, 2, 5, 3, 6, 7],
             [66, 2, 7, 3, 9, 8]]])
print(x.shape)
x.ndim

(3, 2, 6)


3

## Reshape

In [20]:
x = np.array([[0, 1],
          [2, 3],
          [4, 5],
          [6, 7],
          [6, 7],
          ])
x.shape

(5, 2)

In [24]:
x.reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [6],
       [7]])

In [25]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 6, 7]])

In [26]:
np.transpose(x)

array([[0, 2, 4, 6, 6],
       [1, 3, 5, 7, 7]])

In [27]:
x.T

array([[0, 2, 4, 6, 6],
       [1, 3, 5, 7, 7]])