In [1]:
import numpy as np

In [4]:
escalar = 5.679
vector = np.array([3,4,5])
matriz = np.array([[1,2],[3,4],[5,6]])

In [5]:
A = vector + matriz

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [6]:
A = matriz.T + vector

In [7]:
print(A)

[[ 4  7 10]
 [ 5  8 11]]


In [8]:
C = matriz + 42

In [9]:
print(C)

[[43 44]
 [45 46]
 [47 48]]


In [11]:
D = matriz + np.array([[42],[42], [42]])
print(D)

[[43 44]
 [45 46]
 [47 48]]
