In [39]:
import numpy as np

In [40]:
matriz = np.array([[1,0,0],
                [0,1,0],
                [0,0,1]
                ])

print(matriz)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [41]:
print(matriz[:,0].dot(matriz[:,1]))

0


In [42]:
print(matriz[:,0].dot(matriz[:,2]))

0


In [43]:
print(matriz[:,1].dot(matriz[:,2]))

0


In [44]:
print(np.linalg.norm(matriz[:,0]))
print(np.linalg.norm(matriz[:,1]))
print(np.linalg.norm(matriz[:,2]))


1.0
1.0
1.0


In [45]:
print(matriz[0,:].dot(matriz[1,:]))
print(matriz[0,:].dot(matriz[2,:]))
print(matriz[1,:].dot(matriz[2,:]))

0
0
0


In [46]:
print(np.linalg.norm(matriz[0,:]))
print(np.linalg.norm(matriz[1,:]))
print(np.linalg.norm(matriz[2,:]))

1.0
1.0
1.0


In [47]:
A = np.array([[np.cos(100), -np.sin(100)],
            [np.sin(100), -np.cos(100)]])

print(A)

[[ 0.86231887  0.50636564]
 [-0.50636564 -0.86231887]]


In [48]:
print(np.linalg.norm(A[0,:]))
print(np.linalg.norm(A[1,:]))
print(np.linalg.norm(A[:,0]))
print(np.linalg.norm(A[:,1]))

0.9999999999999999
0.9999999999999999
0.9999999999999999
0.9999999999999999


In [49]:
print(A[0,:].dot(A[1,:]))
print(A[:,0].dot(A[:,1]))

-0.8732972972139945
0.8732972972139945


In [50]:
A_t = A.T
print(A_t.dot(A))
print(A.dot(A_t))

[[1.        0.8732973]
 [0.8732973 1.       ]]
[[ 1.        -0.8732973]
 [-0.8732973  1.       ]]


In [51]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 1.7699932   1.03936464]
 [-1.03936464 -1.7699932 ]]


In [52]:
print(A_t)

[[ 0.86231887 -0.50636564]
 [ 0.50636564 -0.86231887]]


In [53]:
print(1/A_t.dot(A))

[[1.         1.14508542]
 [1.14508542 1.        ]]
