In [ ]:
import numpy as np

In [2]:
A = np.array([[3,2],[4,1]])
print(A)

[[3 2]
 [4 1]]


In [3]:
autovalores, autovectores = np.linalg.eig(A)

In [4]:
print(autovalores)
print(autovectores)

[ 5. -1.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [5]:
A_calc = autovectores.dot(np.diag(autovalores)).dot(np.linalg.inv(autovectores))

In [6]:
print(A_calc)

[[3. 2.]
 [4. 1.]]


In [7]:
A = np.array([[3,2],[2,3]])
print(A)

[[3 2]
 [2 3]]


In [8]:
print(A == A.T)

[[ True  True]
 [ True  True]]


In [9]:
autovalores, autovectores = np.linalg.eig(A)
print(autovalores)
print(autovectores)

[5. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [10]:
A_calc = autovectores.dot(np.diag(autovalores)).dot(autovectores.T)
print(A_calc)

[[3. 2.]
 [2. 3.]]
